// dd-tracer.js — Datadog APM Initialization
// Auto-generated by Dobeu Automation Architect
// IMPORTANT: Import this FIRST in your app entry point (index.js, server.js, app.js)
//   require('./dd-tracer')  // Must be the VERY FIRST require
//
// Required env vars:
//   DD_AGENT_HOST=localhost (or datadog-agent if using Docker sidecar)
//   DD_ENV=production|staging|development
//   DD_SERVICE=your-service-name (auto-detected from package.json if unset)
//   DD_VERSION=1.0.0

const tracer = require('dd-trace').init({
  service: process.env.DD_SERVICE || process.env.npm_package_name || 'dobeu-service',
  env: process.env.DD_ENV || 'production',
  version: process.env.DD_VERSION || '1.0.0',
  logInjection: true,
  runtimeMetrics: true,
  profiling: true,
  appsec: true,
});

module.exports = tracer;
